= Hardware specifications

Where did your run your tests? A laptop, or goldengate?

*Goldengate*

What are the performance specifications of the machine: number and speed of
processors, size of RAM? (use `lscpu` and `free -m`)

*Number and speed of processors:*

CPU(s):                          64

Model name:                      Intel(R) Xeon(R) Gold 6246R CPU @ 3.40GHz

CPU MHz:                         1200.049  

CPU max MHz:                     4100.0000  

CPU min MHz:                     1200.0000 


*size of RAM:*

              total        used        free      shared  buff/cache   available  
Mem:          95320       11217       70958           4       13145       83268  
Swap:          8191        1167        7024  


= Allocations

In `simple.c`, where does the increase in 1040 bytes come from?
Why is the value 1040 bytes?

*1040 bytes comes from calling printf. printf calls malloc internally to allocate a buffer for stdout. 
the allocated memory has size of 1040 bytes*

How many bytes does `mylloc_list.c` allocate when the program ends? Explain why
this amount makes sense.

*116 bytes. This is because we malloc and free 10 times, so the same block of memory is reused 10 times. 
At the end of the program, that one memory block is still there and has the size of 116 bytes. This size comes from 
100 bytes that we pass into malloc(), plus 16 bytes for the size of struc chunk*


= Fragementation

*1.* +
Fragementation is when the free memory space is broken into little pieces so the size is too small to 
use and memory blocks remains unused.

Internal fragmentation: The assigned memory block is bigger than the size of memory in use (bigger than what weed), 
which causes the remaining of the memory block to be left unused.
	
External fragmentation: The total memory space is enough for the request of memory, but it is not contiguous so cannot be used.

*2. Output of benchmark1*

The initial top of the heap is 0x7fdcabc16000. +
0 +
The current top of the heap is 0x7fdcabc1fc68.

Increased by 39 (0x27) byte

1

The current top of the heap is 0x7fdcabc1fc68.

Increased by 39 (0x27) byte

2

The current top of the heap is 0x7fdcabc1fc68.

Increased by 39 (0x27) byte

3

The current top of the heap is 0x7fdcabc1fc68.

Increased by 39 (0x27) byte

4

The current top of the heap is 0x7fdcabc1fc68.

Increased by 39 (0x27) byte

5

The current top of the heap is 0x7fdcabc1fc68.

Increased by 39 (0x27) byte

6

The current top of the heap is 0x7fdcabc1fc68.

Increased by 39 (0x27) byte

7

The current top of the heap is 0x7fdcabc1fc68.

Increased by 39 (0x27) byte

8

The current top of the heap is 0x7fdcabc1fc68.

Increased by 39 (0x27) byte

9

The current top of the heap is 0x7fdcabc1fc68.

Increased by 39 (0x27) byte

3. Output of benchmark2

The initial top of the heap is 0x7f3b127c4000.
Total blocks: 161        Free: 103       Used: 58
Internal unused: total: 178682   average: 3080.724121    smallest: 511   largest: 3979
External unused: total: 144345   average: 1401.407715    smallest: 10    largest: 3984
0
The current top of the heap is 0x7f3b1281a527.
Increased by 345 (0x159) Kbyte
Total blocks: 167        Free: 113       Used: 54
Internal unused: total: 159454   average: 2952.851807    smallest: 107   largest: 3991
External unused: total: 177549   average: 1571.230103    smallest: 10    largest: 3984
1
The current top of the heap is 0x7f3b12820327.
Increased by 368 (0x170) Kbyte
Total blocks: 169        Free: 117       Used: 52
Internal unused: total: 157088   average: 3020.923096    smallest: 129   largest: 3977
External unused: total: 189341   average: 1618.299194    smallest: 10    largest: 3997
2
The current top of the heap is 0x7f3b12822282.
Increased by 376 (0x178) Kbyte
Total blocks: 172        Free: 120       Used: 52
Internal unused: total: 160672   average: 3089.846191    smallest: 146   largest: 3989
External unused: total: 201235   average: 1676.958374    smallest: 10    largest: 3998
3
The current top of the heap is 0x7f3b12825188.
Increased by 388 (0x184) Kbyte
Total blocks: 175        Free: 125       Used: 50
Internal unused: total: 145974   average: 2919.479980    smallest: 6     largest: 3984
External unused: total: 222205   average: 1777.640015    smallest: 10    largest: 3999
4
The current top of the heap is 0x7f3b12828095.
Increased by 400 (0x190) Kbyte
Total blocks: 176        Free: 116       Used: 60
Internal unused: total: 191611   average: 3193.516602    smallest: 984   largest: 3986
External unused: total: 189140   average: 1630.517212    smallest: 10    largest: 3999
5
The current top of the heap is 0x7f3b12829045.
Increased by 404 (0x194) Kbyte
Total blocks: 176        Free: 128       Used: 48
Internal unused: total: 153391   average: 3195.645752    smallest: 381   largest: 3991
External unused: total: 227231   average: 1775.242188    smallest: 10    largest: 4000
6
The current top of the heap is 0x7f3b12829045.
Increased by 404 (0x194) Kbyte
Total blocks: 177        Free: 125       Used: 52
Internal unused: total: 154837   average: 2977.634521    smallest: 138   largest: 3989
External unused: total: 219943   average: 1759.543945    smallest: 10    largest: 3999
7
The current top of the heap is 0x7f3b12829ff5.
Increased by 407 (0x197) Kbyte
Total blocks: 178        Free: 118       Used: 60
Internal unused: total: 193404   average: 3223.399902    smallest: 401   largest: 3990
External unused: total: 193697   average: 1641.500000    smallest: 10    largest: 4000
8
The current top of the heap is 0x7f3b1282afa5.
Increased by 411 (0x19b) Kbyte
Total blocks: 178        Free: 130       Used: 48
Internal unused: total: 150237   average: 3129.937500    smallest: 636   largest: 3987
External unused: total: 237661   average: 1828.161499    smallest: 10    largest: 4000
9
The current top of the heap is 0x7f3b1282afa5.
Increased by 411 (0x19b) Kbyte